<?php
require __DIR__ . '/bootstrap.php';
$id = filter_input(INPUT_GET, 'id', FILTER_VALIDATE_INT);
$stmt = db()->prepare('SELECT * FROM offices WHERE id=:id AND is_active=1'); $stmt->execute(['id'=>$id]); $office=$stmt->fetch();
if(!$office){ http_response_code(404); $pageTitle='Office not found'; require __DIR__.'/partials/header.php'; echo '<div class="mx-auto max-w-3xl px-4 py-20 text-center"><h1 class="text-3xl font-black text-tesda-navy">Office not found</h1><a class="mt-5 inline-block font-bold text-tesda-blue" href="'.url().'">Return to directory</a></div>'; require __DIR__.'/partials/footer.php'; exit; }
$stmt=db()->prepare('SELECT * FROM officials WHERE office_id=:id ORDER BY is_primary DESC, sort_order, name'); $stmt->execute(['id'=>$id]); $officials=$stmt->fetchAll();
$pageTitle=$office['name'].' | TESDA Directory'; require __DIR__.'/partials/header.php';
?>
<section class="bg-tesda-navy text-white"><div class="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8"><a href="<?= url() ?>" class="text-sm font-bold text-blue-200 hover:text-white">← Back to directory</a><span class="mt-6 block text-sm font-bold uppercase tracking-[.16em] text-blue-200"><?= e($office['office_type']) ?></span><h1 class="mt-2 text-3xl font-black tracking-tight sm:text-4xl"><?= e($office['name']) ?></h1><?php if($office['region_name']): ?><p class="mt-3 text-blue-100"><?= e($office['region_name']) ?></p><?php endif; ?></div></section>
<section class="mx-auto grid max-w-5xl gap-6 px-4 py-8 sm:px-6 lg:grid-cols-[1fr_340px] lg:px-8">
  <div class="rounded-2xl border border-slate-200 bg-white p-6 sm:p-8"><h2 class="text-xl font-extrabold text-tesda-navy">Officials</h2><div class="mt-5 divide-y divide-slate-100"><?php foreach($officials as $official): ?><div class="py-5 first:pt-0"><div class="flex gap-4"><?php if($official['photo_path']): ?><img src="<?= e(photo_url($official['photo_path'])) ?>" alt="Portrait of <?= e($official['name']) ?>" loading="lazy" decoding="async" class="h-16 w-16 shrink-0 rounded-full object-cover"><?php else: ?><div class="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-blue-50 font-black text-tesda-blue"><?= e(mb_substr($official['name'],0,1)) ?></div><?php endif; ?><div><h3 class="font-extrabold uppercase tracking-wide text-slate-900"><a href="<?= url('official.php?id='.(int)$official['id']) ?>" class="hover:text-tesda-blue hover:underline"><?= e($official['name']) ?></a></h3><p class="mt-1 italic text-slate-500"><?= e($official['position']) ?></p><?php if($official['email']): ?><a class="mt-2 block text-sm font-semibold text-tesda-blue hover:underline" href="mailto:<?= e($official['email']) ?>"><?= e($official['email']) ?></a><?php endif; ?></div></div></div><?php endforeach; ?><?php if(!$officials): ?><p class="py-5 text-slate-500">No officials are listed yet.</p><?php endif; ?></div></div>
  <aside class="h-fit rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-lg font-extrabold text-tesda-navy">Contact information</h2><dl class="mt-5 space-y-5 text-sm"><div><dt class="font-bold text-slate-500">Address</dt><dd class="mt-1 leading-6 text-slate-800"><?= e($office['address']) ?></dd></div><?php foreach(['telephone'=>'Telephone','fax'=>'Fax','email'=>'Email','website'=>'Website'] as $key=>$label): if($office[$key]): ?><div><dt class="font-bold text-slate-500"><?= $label ?></dt><dd class="mt-1 text-slate-800"><?php if($key==='email'): ?><a class="text-tesda-blue hover:underline" href="mailto:<?= e($office[$key]) ?>"><?= e($office[$key]) ?></a><?php elseif($key==='website'): ?><a class="break-all text-tesda-blue hover:underline" href="<?= e($office[$key]) ?>" target="_blank" rel="noopener"><?= e($office[$key]) ?></a><?php else: ?><?= e($office[$key]) ?><?php endif; ?></dd></div><?php endif; endforeach; ?></dl></aside>
</section>
<?php require __DIR__.'/partials/footer.php'; ?>
