<?php
require dirname(__DIR__).'/bootstrap.php'; require_admin();
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT) ?: filter_input(INPUT_POST,'id',FILTER_VALIDATE_INT);
$office=['name'=>'','office_type'=>'Regional Office','region_code'=>'','region_name'=>'','address'=>'','telephone'=>'','fax'=>'','email'=>'','website'=>'','sort_order'=>0,'is_active'=>1];
if($id){$stmt=db()->prepare('SELECT * FROM offices WHERE id=:id');$stmt->execute(['id'=>$id]);$office=$stmt->fetch()?:$office;}
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();
 $payload=[];
 foreach(['name','office_type','region_code','region_name','address','telephone','fax','email','website','sort_order'] as $key){$payload[$key]=trim((string)($_POST[$key]??''));}
 $payload['is_active']=isset($_POST['is_active'])?1:0;
 if($id){$sql='UPDATE offices SET name=:name,office_type=:office_type,region_code=:region_code,region_name=:region_name,address=:address,telephone=:telephone,fax=:fax,email=:email,website=:website,sort_order=:sort_order,is_active=:is_active WHERE id=:id';$payload['id']=$id;}else{$sql='INSERT INTO offices (name,office_type,region_code,region_name,address,telephone,fax,email,website,sort_order,is_active) VALUES (:name,:office_type,:region_code,:region_name,:address,:telephone,:fax,:email,:website,:sort_order,:is_active)';}
 db()->prepare($sql)->execute($payload); flash('success',$id?'Office updated.':'Office added.'); redirect('admin/index.php');
}
$pageTitle=($id?'Edit':'Add').' office | TESDA'; require dirname(__DIR__).'/partials/header.php';
?>
<section class="mx-auto max-w-4xl px-4 py-8 sm:px-6 lg:px-8"><a href="<?= url('admin/index.php') ?>" class="text-sm font-bold text-tesda-blue">← Back to management</a><div class="mt-5 rounded-2xl border border-slate-200 bg-white p-6 sm:p-8"><h1 class="text-2xl font-black text-tesda-navy"><?= $id?'Edit office':'Add office' ?></h1><form method="post" class="mt-7 grid gap-5 sm:grid-cols-2"><input type="hidden" name="_token" value="<?= csrf_token() ?>"><input type="hidden" name="id" value="<?= (int)$id ?>"><div class="sm:col-span-2"><label class="label">Office name</label><input class="field" name="name" required value="<?= e($office['name']) ?>"></div><div><label class="label">Office type</label><select class="field" name="office_type"><?php foreach(['Central Office','Regional Office','Provincial Office','TESDA Technology Institution'] as $t): ?><option <?= $office['office_type']===$t?'selected':'' ?>><?= $t ?></option><?php endforeach; ?></select></div><div><label class="label">Sort order</label><input class="field" name="sort_order" type="number" value="<?= (int)$office['sort_order'] ?>"></div><div><label class="label">Region code</label><input class="field" name="region_code" value="<?= e($office['region_code']) ?>" placeholder="e.g. NCR"></div><div><label class="label">Region name</label><input class="field" name="region_name" value="<?= e($office['region_name']) ?>" placeholder="e.g. National Capital Region"></div><div class="sm:col-span-2"><label class="label">Address</label><textarea class="field" name="address" rows="3"><?= e($office['address']) ?></textarea></div><?php foreach(['telephone'=>'Telephone','fax'=>'Fax','email'=>'Email','website'=>'Website'] as $key=>$label): ?><div><label class="label"><?= $label ?></label><input class="field" name="<?= $key ?>" <?= $key==='email'?'type="email"':'' ?> value="<?= e($office[$key]) ?>"></div><?php endforeach; ?><label class="sm:col-span-2 flex items-center gap-3 font-semibold text-slate-700"><input class="h-4 w-4 accent-blue-700" type="checkbox" name="is_active" <?= $office['is_active']?'checked':'' ?>>Visible in public directory</label><div class="sm:col-span-2 flex justify-end"><button class="rounded-xl bg-tesda-blue px-6 py-3 font-bold text-white hover:bg-tesda-navy">Save office</button></div></form></div></section>
<?php require dirname(__DIR__).'/partials/footer.php'; ?>
