<?php
require dirname(__DIR__).'/bootstrap.php'; require_admin();
$officeId=filter_input(INPUT_GET,'office_id',FILTER_VALIDATE_INT) ?: filter_input(INPUT_POST,'office_id',FILTER_VALIDATE_INT);
$stmt=db()->prepare('SELECT * FROM offices WHERE id=:id');$stmt->execute(['id'=>$officeId]);$office=$stmt->fetch();if(!$office)redirect('admin/index.php');
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=$_POST['action']??'';$officialId=filter_input(INPUT_POST,'official_id',FILTER_VALIDATE_INT);
 if($action==='delete'&&$officialId){db()->prepare('DELETE FROM officials WHERE id=:id AND office_id=:office')->execute(['id'=>$officialId,'office'=>$officeId]);flash('success','Official removed.');}
 else{$name=trim($_POST['name']??'');$position=trim($_POST['position']??'');$email=trim($_POST['email']??'');$primary=isset($_POST['is_primary'])?1:0;if($primary)db()->prepare('UPDATE officials SET is_primary=0 WHERE office_id=:id')->execute(['id'=>$officeId]);if($officialId){db()->prepare('UPDATE officials SET name=:name,position=:position,email=:email,is_primary=:primary WHERE id=:id AND office_id=:office')->execute(['name'=>$name,'position'=>$position,'email'=>$email,'primary'=>$primary,'id'=>$officialId,'office'=>$officeId]);}else{db()->prepare('INSERT INTO officials (office_id,name,position,email,is_primary) VALUES (:office,:name,:position,:email,:primary)')->execute(['office'=>$officeId,'name'=>$name,'position'=>$position,'email'=>$email,'primary'=>$primary]);}flash('success',$officialId?'Official updated.':'Official added.');}
 redirect('admin/officials.php?office_id='.$officeId);
}
$edit=null;if(isset($_GET['edit'])){$stmt=db()->prepare('SELECT * FROM officials WHERE id=:id AND office_id=:office');$stmt->execute(['id'=>(int)$_GET['edit'],'office'=>$officeId]);$edit=$stmt->fetch();}
$stmt=db()->prepare('SELECT * FROM officials WHERE office_id=:id ORDER BY is_primary DESC,sort_order,name');$stmt->execute(['id'=>$officeId]);$officials=$stmt->fetchAll();
$pageTitle='Officials | '.$office['name'];require dirname(__DIR__).'/partials/header.php';
?>
<section class="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8"><a href="<?= url('admin/index.php') ?>" class="text-sm font-bold text-tesda-blue">← Back to management</a><h1 class="mt-5 text-3xl font-black text-tesda-navy"><?= e($office['name']) ?></h1><p class="mt-2 text-slate-500">Manage the officials listed under this office.</p><div class="mt-8 grid gap-6 lg:grid-cols-[380px_1fr]"><form method="post" class="h-fit rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-xl font-extrabold text-tesda-navy"><?= $edit?'Edit official':'Add official' ?></h2><input type="hidden" name="_token" value="<?= csrf_token() ?>"><input type="hidden" name="office_id" value="<?= (int)$officeId ?>"><input type="hidden" name="official_id" value="<?= (int)($edit['id']??0) ?>"><div class="mt-5 space-y-4"><div><label class="label">Full name</label><input class="field" name="name" required value="<?= e($edit['name']??'') ?>"></div><div><label class="label">Position</label><input class="field" name="position" required value="<?= e($edit['position']??'') ?>"></div><div><label class="label">Email</label><input class="field" name="email" type="email" value="<?= e($edit['email']??'') ?>"></div><label class="flex items-center gap-3 font-semibold text-slate-700"><input type="checkbox" name="is_primary" class="h-4 w-4 accent-blue-700" <?= !empty($edit['is_primary'])?'checked':'' ?>>Primary official</label><button class="w-full rounded-xl bg-tesda-blue px-5 py-3 font-bold text-white"><?= $edit?'Update':'Add' ?> official</button></div></form><div class="space-y-3"><?php foreach($officials as $o): ?><div class="rounded-xl border border-slate-200 bg-white p-5"><div class="flex flex-wrap items-start justify-between gap-4"><div><h3 class="font-extrabold uppercase tracking-wide text-slate-900"><?= e($o['name']) ?></h3><p class="mt-1 italic text-slate-500"><?= e($o['position']) ?></p><?php if($o['is_primary']): ?><span class="mt-2 inline-block rounded-full bg-blue-50 px-2 py-1 text-xs font-bold text-tesda-blue">Primary official</span><?php endif; ?></div><div><a class="font-bold text-tesda-blue" href="?office_id=<?= (int)$officeId ?>&edit=<?= (int)$o['id'] ?>">Edit</a><form method="post" class="ml-3 inline" onsubmit="return confirm('Remove this official?')"><input type="hidden" name="_token" value="<?= csrf_token() ?>"><input type="hidden" name="office_id" value="<?= (int)$officeId ?>"><input type="hidden" name="official_id" value="<?= (int)$o['id'] ?>"><input type="hidden" name="action" value="delete"><button class="font-bold text-red-600">Remove</button></form></div></div></div><?php endforeach; ?><?php if(!$officials): ?><div class="rounded-xl border border-dashed border-slate-300 p-8 text-center text-slate-500">No officials added yet.</div><?php endif; ?></div></div></section>
<?php require dirname(__DIR__).'/partials/footer.php'; ?>

